language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.3.1
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q pymongo
  - python setup.py -q install
before_script:
#  - mysql -e 'create database myapp_test;'
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
script:
  - python setup.py test
